wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1679600873.779522
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.14.0
      8:
      - 1
      - 5
architecture:
  desc: null
  value: XGBoost
balanced:
  desc: null
  value: 'true'
features:
  desc: null
  value:
  - extraction_type
  - payment_type
  - quantity
  - source_type
  - waterpoint_type_group
  - cat_funder
  - construction_decade
  - consistent_water
  - age
  - season
  - water_quality
  - cat_installer
  - gps_height_zscorenormalise
  - population
  - zones
  - source_below_sea_level
params:
  desc: null
  value:
    colsample_bytree: 1
    gamma: 0
    learning_rate: 0.3
    max_depth: 9
    min_child_weight: 1
    n_estimators: 200
    reg_alpha: 1
    reg_lambda: 1.0e-05
    subsample: 0.8
